<a href="https://colab.research.google.com/github/gschnitkey/PCM/blob/main/create2015_2025FieldData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Create Field Data

I used this file to read data that Laura gave me and produce a file that I will use for my analysis.  The data came to me in May 10, 2026.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np


from google.colab import data_table
data_table.enable_dataframe_formatter()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
'''
The following file came from Laura. I got this on May 10, 2026. It includes data for the
past years: 2015 to 2025.
'''

fldData = pd.read_excel('/content/drive/MyDrive/data/pcm-2025/2015-2025 PCM by-field - to GS.xlsx')

fldData

Warning: total number of rows (49904) exceeds max_rows (20000). Falling back to pandas display.

,farmer_id,primary_specialist_id,field_id,season_id,is_pcm_program_analysis,retroactive_unlock_reason,data_exclusion_reason,cropping_system,growing_season,crop_type,...,riparian,saturated_riparian,terracing,sediment_basins,wetland,bioreactors,drainage_water,drainage_cl,drainage,wind_barrier
0,ee29cd59-0106-4e45-ba81-94b952b368eb,525f5ec2-ef74-43c4-9181-a839000e9934,4dba6c02-6c2a-11e9-a566-cb00e80f14c8,14e2ac00-8b65-11ec-8cca-7c00110b2af0,True,NaN,NaN,soybeansSeed,2019,soybeansSeed,...,False,False,False,False,False,False,False,Somewhat poorly drained,plastic,False
1,ee29cd59-0106-4e45-ba81-94b952b368eb,525f5ec2-ef74-43c4-9181-a839000e9934,6f612401-5a9b-11eb-8336-0b00103e51a2,d925f882-f83a-11ee-9f82-ad0011cfc0c9,True,NaN,NaN,soybeansSeed,2019,soybeansSeed,...,False,False,False,False,False,False,False,Somewhat poorly drained,none,False
2,22fafe12-bcbb-4910-9fef-5ce1e3d3293b,525f5ec2-ef74-43c4-9181-a839000e9934,07808501-6aff-11eb-8c08-250011af7f68,a6bad202-95c5-11ec-a343-ce0011478079,True,NaN,NaN,corn,2020,corn,...,False,False,False,False,False,False,False,Somewhat poorly drained,none,False
3,22fafe12-bcbb-4910-9fef-5ce1e3d3293b,525f5ec2-ef74-43c4-9181-a839000e9934,7f601c00-e726-11ea-b4ce-5000112267f7,ba0d5d81-397f-11eb-941d-7d00105fbeed,True,NaN,NaN,corn,2020,corn,...,False,False,False,False,False,False,False,Somewhat poorly drained,plastic,False
4,25318381-0664-40f2-9e03-fbd23c2b262d,67cb56df-a2c8-4051-a586-f396e319bfb1,02bc4b03-cebc-11eb-86e4-3f000f091d8c,44d59782-f907-11ee-9f82-ad0011cffb55,True,NaN,NaN,soybeans,2020,soybeans,...,False,False,False,False,False,False,False,Somewhat poorly drained,none,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49899,ffca1972-d92e-42fe-9f34-e9896594ee96,525f5ec2-ef74-43c4-9181-a839000e9934,f973e900-e950-11ea-b4ce-50001122f2a4,13533d00-eb98-11ea-b4ce-500011230147,True,NaN,NaN,soybeans,2020,soybeans,...,False,False,False,False,False,False,False,Poorly drained,none,False
49900,ffca1972-d92e-42fe-9f34-e9896594ee96,525f5ec2-ef74-43c4-9181-a839000e9934,f973e900-e950-11ea-b4ce-50001122f2a4,b6598600-eb9b-11ea-b4ce-50001123074b,True,NaN,NaN,corn,2019,corn,...,False,False,False,False,False,False,False,Poorly drained,none,False
49901,ffca1972-d92e-42fe-9f34-e9896594ee96,525f5ec2-ef74-43c4-9181-a839000e9934,ffb69500-e951-11ea-b4ce-50001122f2a8,151d0080-eb98-11ea-b4ce-50001123018a,True,NaN,NaN,soybeans,2020,soybeans,...,False,False,False,False,False,False,False,Poorly drained,plastic,False
49902,ffca1972-d92e-42fe-9f34-e9896594ee96,525f5ec2-ef74-43c4-9181-a839000e9934,ffb69500-e951-11ea-b4ce-50001122f2a8,df12a900-7b22-11ed-8f2e-e1001108db50,False,NaN,NaN,soybeansSeed,2021,soybeansSeed,...,False,False,False,False,False,False,False,Poorly drained,plastic,False
49903,ffca1972-d92e-42fe-9f34-e9896594ee96,525f5ec2-ef74-43c4-9181-a839000e9934,ffb69500-e951-11ea-b4ce-50001122f2a8,e449b680-eb18-11ea-b4ce-50001122f94b,True,NaN,NaN,corn,2019,corn,...,False,False,False,False,False,False,False,Poorly drained,plastic,False

In [ ]:
'''
These are the names of the fields.  I copied this over into an
Excel spreadsheet to rename the files.
'''
colNames = pd.DataFrame(fldData.columns, columns=['Field'])
colNames

                      Field
0                 farmer_id
1     primary_specialist_id
2                  field_id
3                 season_id
4   is_pcm_program_analysis
..                      ...
82              bioreactors
83           drainage_water
84              drainage_cl
85                 drainage
86             wind_barrier

[87 rows x 1 columns]

In [ ]:
'''
The following frame gives the original field name (field), my newField name, and whether
to keep it or not.  The "field" was copied from the above cell to make the fieldDataMapping.xlsx

'''
newFieldNames = pd.read_excel('/content/drive/MyDrive/data/pcm-2025/fieldDataNameMapping.xlsx')
newFieldNames

                      field               newField keep
0                 farmer_id                farmIdO  Yes
1     primary_specialist_id  primary_specialist_id   No
2                  field_id               fieldIdO  Yes
3                 season_id              season_id   No
4   is_pcm_program_analysis               pcmField  Yes
..                      ...                    ...  ...
82              bioreactors            bioreactors   No
83           drainage_water         drainage_water   No
84              drainage_cl                drainCl  Yes
85                 drainage              drainType  Yes
86             wind_barrier           wind_barrier   No

[87 rows x 3 columns]

In [ ]:
'''
The following code renames the columns in the field to my new names

'''
for index, row in newFieldNames.iterrows():
  fldData.rename(columns={row['field']: row['newField']}, inplace=True)

fldData

Warning: total number of rows (49904) exceeds max_rows (20000). Falling back to pandas display.

,farmIdO,primary_specialist_id,fieldIdO,season_id,pcmField,retroactive_unlock_reason,data_exclusion_reason,system,year,crop,...,riparian,saturated_riparian,terracing,sediment_basins,wetland,bioreactors,drainage_water,drainCl,drainType,wind_barrier
0,ee29cd59-0106-4e45-ba81-94b952b368eb,525f5ec2-ef74-43c4-9181-a839000e9934,4dba6c02-6c2a-11e9-a566-cb00e80f14c8,14e2ac00-8b65-11ec-8cca-7c00110b2af0,True,NaN,NaN,soybeansSeed,2019,soybeansSeed,...,False,False,False,False,False,False,False,Somewhat poorly drained,plastic,False
1,ee29cd59-0106-4e45-ba81-94b952b368eb,525f5ec2-ef74-43c4-9181-a839000e9934,6f612401-5a9b-11eb-8336-0b00103e51a2,d925f882-f83a-11ee-9f82-ad0011cfc0c9,True,NaN,NaN,soybeansSeed,2019,soybeansSeed,...,False,False,False,False,False,False,False,Somewhat poorly drained,none,False
2,22fafe12-bcbb-4910-9fef-5ce1e3d3293b,525f5ec2-ef74-43c4-9181-a839000e9934,07808501-6aff-11eb-8c08-250011af7f68,a6bad202-95c5-11ec-a343-ce0011478079,True,NaN,NaN,corn,2020,corn,...,False,False,False,False,False,False,False,Somewhat poorly drained,none,False
3,22fafe12-bcbb-4910-9fef-5ce1e3d3293b,525f5ec2-ef74-43c4-9181-a839000e9934,7f601c00-e726-11ea-b4ce-5000112267f7,ba0d5d81-397f-11eb-941d-7d00105fbeed,True,NaN,NaN,corn,2020,corn,...,False,False,False,False,False,False,False,Somewhat poorly drained,plastic,False
4,25318381-0664-40f2-9e03-fbd23c2b262d,67cb56df-a2c8-4051-a586-f396e319bfb1,02bc4b03-cebc-11eb-86e4-3f000f091d8c,44d59782-f907-11ee-9f82-ad0011cffb55,True,NaN,NaN,soybeans,2020,soybeans,...,False,False,False,False,False,False,False,Somewhat poorly drained,none,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49899,ffca1972-d92e-42fe-9f34-e9896594ee96,525f5ec2-ef74-43c4-9181-a839000e9934,f973e900-e950-11ea-b4ce-50001122f2a4,13533d00-eb98-11ea-b4ce-500011230147,True,NaN,NaN,soybeans,2020,soybeans,...,False,False,False,False,False,False,False,Poorly drained,none,False
49900,ffca1972-d92e-42fe-9f34-e9896594ee96,525f5ec2-ef74-43c4-9181-a839000e9934,f973e900-e950-11ea-b4ce-50001122f2a4,b6598600-eb9b-11ea-b4ce-50001123074b,True,NaN,NaN,corn,2019,corn,...,False,False,False,False,False,False,False,Poorly drained,none,False
49901,ffca1972-d92e-42fe-9f34-e9896594ee96,525f5ec2-ef74-43c4-9181-a839000e9934,ffb69500-e951-11ea-b4ce-50001122f2a8,151d0080-eb98-11ea-b4ce-50001123018a,True,NaN,NaN,soybeans,2020,soybeans,...,False,False,False,False,False,False,False,Poorly drained,plastic,False
49902,ffca1972-d92e-42fe-9f34-e9896594ee96,525f5ec2-ef74-43c4-9181-a839000e9934,ffb69500-e951-11ea-b4ce-50001122f2a8,df12a900-7b22-11ed-8f2e-e1001108db50,False,NaN,NaN,soybeansSeed,2021,soybeansSeed,...,False,False,False,False,False,False,False,Poorly drained,plastic,False
49903,ffca1972-d92e-42fe-9f34-e9896594ee96,525f5ec2-ef74-43c4-9181-a839000e9934,ffb69500-e951-11ea-b4ce-50001122f2a8,e449b680-eb18-11ea-b4ce-50001122f94b,True,NaN,NaN,corn,2019,corn,...,False,False,False,False,False,False,False,Poorly drained,plastic,False

In [ ]:
'''
The following code deletes the variables that I do not want to keep

'''

for index, row in newFieldNames.iterrows():
  if row['keep'] == 'No':
    fldData.drop(columns=[row['newField']], inplace=True)

fldData

Warning: total number of rows (49904) exceeds max_rows (20000). Falling back to pandas display.

,farmIdO,fieldIdO,pcmField,system,year,crop,acres,stateNm,ctyNm,mrtnLoc,...,phos,pot,lime,irr,irrApp,irrigation_acres,irrigation_depth,irrigation_pressure,drainCl,drainType
0,ee29cd59-0106-4e45-ba81-94b952b368eb,4dba6c02-6c2a-11e9-a566-cb00e80f14c8,True,soybeansSeed,2019,soybeansSeed,50.253,Illinois,McLean County,Central Illinois,...,0.00,0.0,0.00,False,0.0,0.0,0,0,Somewhat poorly drained,plastic
1,ee29cd59-0106-4e45-ba81-94b952b368eb,6f612401-5a9b-11eb-8336-0b00103e51a2,True,soybeansSeed,2019,soybeansSeed,53.225,Illinois,McLean County,Central Illinois,...,0.00,0.0,0.00,False,0.0,0.0,0,0,Somewhat poorly drained,none
2,22fafe12-bcbb-4910-9fef-5ce1e3d3293b,07808501-6aff-11eb-8c08-250011af7f68,True,corn,2020,corn,32.170,Illinois,Livingston County,Central Illinois,...,36.40,54.0,0.00,False,0.0,0.0,0,0,Somewhat poorly drained,none
3,22fafe12-bcbb-4910-9fef-5ce1e3d3293b,7f601c00-e726-11ea-b4ce-5000112267f7,True,corn,2020,corn,35.379,Illinois,Livingston County,Central Illinois,...,36.40,54.0,0.00,False,0.0,0.0,0,0,Somewhat poorly drained,plastic
4,25318381-0664-40f2-9e03-fbd23c2b262d,02bc4b03-cebc-11eb-86e4-3f000f091d8c,True,soybeans,2020,soybeans,39.950,Illinois,Champaign County,Central Illinois,...,0.00,0.0,0.00,False,0.0,0.0,0,0,Somewhat poorly drained,none
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49899,ffca1972-d92e-42fe-9f34-e9896594ee96,f973e900-e950-11ea-b4ce-50001122f2a4,True,soybeans,2020,soybeans,160.000,Illinois,Ford County,Central Illinois,...,0.00,0.0,0.00,False,0.0,0.0,0,0,Poorly drained,none
49900,ffca1972-d92e-42fe-9f34-e9896594ee96,f973e900-e950-11ea-b4ce-50001122f2a4,True,corn,2019,corn,160.000,Illinois,Ford County,Central Illinois,...,0.00,0.0,0.00,False,0.0,0.0,0,0,Poorly drained,none
49901,ffca1972-d92e-42fe-9f34-e9896594ee96,ffb69500-e951-11ea-b4ce-50001122f2a8,True,soybeans,2020,soybeans,75.313,Illinois,Ford County,Central Illinois,...,0.00,0.0,778.25,False,0.0,0.0,0,0,Poorly drained,plastic
49902,ffca1972-d92e-42fe-9f34-e9896594ee96,ffb69500-e951-11ea-b4ce-50001122f2a8,False,soybeansSeed,2021,soybeansSeed,75.313,Illinois,Ford County,Central Illinois,...,95.68,139.2,778.25,False,0.0,0.0,0,0,Poorly drained,plastic
49903,ffca1972-d92e-42fe-9f34-e9896594ee96,ffb69500-e951-11ea-b4ce-50001122f2a8,True,corn,2019,corn,75.313,Illinois,Ford County,Central Illinois,...,0.00,130.2,778.25,False,0.0,0.0,0,0,Poorly drained,plastic

In [ ]:
'''
create a new numbering system for farms and fields
'''

farmId = pd.DataFrame(fldData['farmIdO'].unique(), columns=['farmIdO'])
farmId['farmId'] = np.arange(len(farmId))
fldData = pd.merge(fldData, farmId, on='farmIdO', how='left')
fldData

fieldId = pd.DataFrame(fldData['fieldIdO'].unique(), columns=['fieldIdO'])
fieldId['fieldId'] = np.arange(len(fieldId))
fldData = pd.merge(fldData, fieldId, on='fieldIdO', how='left')
fldData

farmId.to_csv('/content/drive/MyDrive/data/pcm-2025/farmId.csv', index=False)
fieldId.to_csv('/content/drive/MyDrive/data/pcm-2025/fieldId.csv', index=False)

In [ ]:
'''
I used this to download and sort into variables that I want to keep
'''

colNames = pd.DataFrame(fldData.columns, columns=['Field'])
colNames

                  Field
0               farmIdO
1              fieldIdO
2              pcmField
3                system
4                  year
5                  crop
6                 acres
7               stateNm
8                 ctyNm
9               mrtnLoc
10                 type
11             seedType
12               tenure
13            sprRating
14             sprClass
15              soilTex
16               manure
17                  yld
18               totYld
19              pltDate
20             pltDate2
21              harDate
22             HarDate2
23             tilScore
24             covCropS
25                nMgtS
26                  rev
27               revTot
28               cstTot
29               dirCst
30               pwrCst
31         covCropPlant
32          covCropSeed
33              nitCost
34          fldWorkCost
35              ovedCst
36           nonLandCst
37                  olr
38             tilStand
39             covStand
40               nBench
41                  nit
42               nueEff
43               nStand
44                 phos
45                  pot
46                 lime
47                  irr
48               irrApp
49     irrigation_acres
50     irrigation_depth
51  irrigation_pressure
52              drainCl
53            drainType
54               farmId
55              fieldId

In [ ]:
'''
The attached file includes the new order for the field names
'''

newOrder = pd.read_excel('/content/drive/MyDrive/data/pcm-2025/mapOfFieldsToKeep.xlsx')
newOrder

    index                Field   Num
0      54               farmId   1.0
1      55              fieldId   2.0
2       4                 year   3.0
3       5                 crop   4.0
4       6                acres   5.0
5       7              stateNm   6.0
6       8                ctyNm   7.0
7       9              mrtnLoc   8.0
8      17                  yld   9.0
9      41                  nit  10.0
10     44                 phos  11.0
11     45                  pot  12.0
12     46                 lime  13.0
13     26                  rev  14.0
14     19              pltDate  14.0
15     36           nonLandCst  15.0
16     21              harDate  15.0
17     37                  olr  16.0
18     43               nStand  16.0
19     29               dirCst  17.0
20     39             covStand  17.0
21     30               pwrCst  18.0
22     38             tilStand  18.0
23     35              ovedCst  19.0
24     40               nBench  19.0
25     33              nitCost  20.0
26      2             pcmField  20.0
27     34          fldWorkCost  21.0
28      3               system  21.0
29     25                nMgtS  21.0
30     31         covCropPlant  22.0
31     10                 type  22.0
32     32          covCropSeed  23.0
33     11             seedType  23.0
34     12               tenure  24.0
35     13            sprRating  25.0
36     14             sprClass  26.0
37     15              soilTex  27.0
38     16               manure  28.0
39     23             tilScore  29.0
40     24             covCropS  39.0
41     52              drainCl  40.0
42     53            drainType  41.0
43     47                  irr  42.0
44      0              farmIdO   NaN
45      1             fieldIdO   NaN
46     18               totYld   NaN
47     20             pltDate2   NaN
48     22             HarDate2   NaN
49     27               revTot   NaN
50     28               cstTot   NaN
51     42               nueEff   NaN
52     48               irrApp   NaN
53     49     irrigation_acres   NaN
54     50     irrigation_depth   NaN
55     51  irrigation_pressure   NaN

In [ ]:
newOrder = newOrder[newOrder['Num'].notna()]

iFirst = True
for index, row in newOrder.iterrows():
  if iFirst:
    print(row['Field'])
    fldDataC = pd.DataFrame(fldData[row['Field']],columns = [row['Field']])
    iFirst = False
  else:
    print(row['Field'])
    fldDataC[row['Field']] = fldData[row['Field']]

fldDataC

farmId
fieldId
year
crop
acres
stateNm
ctyNm
mrtnLoc
yld
nit
phos
pot
lime
rev
pltDate
nonLandCst
harDate
olr
nStand
dirCst
covStand
pwrCst
tilStand
ovedCst
nBench
nitCost
pcmField
fldWorkCost
system
nMgtS
covCropPlant
type
covCropSeed
seedType
tenure
sprRating
sprClass
soilTex
manure
tilScore
covCropS
drainCl
drainType
irr
Warning: total number of rows (49904) exceeds max_rows (20000). Falling back to pandas display.

,farmId,fieldId,year,crop,acres,stateNm,ctyNm,mrtnLoc,yld,nit,...,tenure,sprRating,sprClass,soilTex,manure,tilScore,covCropS,drainCl,drainType,irr
0,0,0,2019,soybeansSeed,50.253,Illinois,McLean County,Central Illinois,69.00,0.000,...,own,141.73,HIGH,Silt loam,False,35,1.0,Somewhat poorly drained,plastic,False
1,0,1,2019,soybeansSeed,53.225,Illinois,McLean County,Central Illinois,69.00,0.000,...,own,141.82,HIGH,Silt loam,False,35,1.0,Somewhat poorly drained,none,False
2,1,2,2020,corn,32.170,Illinois,Livingston County,Central Illinois,142.00,195.402,...,Blank,115.52,LOW,Silty clay loam,False,40,1.0,Somewhat poorly drained,none,False
3,1,3,2020,corn,35.379,Illinois,Livingston County,Central Illinois,142.00,195.402,...,rent,117.50,LOW,Silty clay loam,False,40,1.0,Somewhat poorly drained,plastic,False
4,2,4,2020,soybeans,39.950,Illinois,Champaign County,Central Illinois,71.28,0.000,...,Blank,143.13,HIGH,Silt loam,False,35,1.0,Somewhat poorly drained,none,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49899,342,3320,2020,soybeans,160.000,Illinois,Ford County,Central Illinois,55.20,0.000,...,rent,118.18,LOW,Silty clay,False,100,1.0,Poorly drained,none,False
49900,342,3320,2019,corn,160.000,Illinois,Ford County,Central Illinois,130.00,170.002,...,rent,118.18,LOW,Silty clay,False,93,1.0,Poorly drained,none,False
49901,342,4340,2020,soybeans,75.313,Illinois,Ford County,Central Illinois,58.40,0.000,...,sold,122.12,LOW,Silty clay,False,100,1.0,Poorly drained,plastic,False
49902,342,4340,2021,soybeansSeed,75.313,Illinois,Ford County,Central Illinois,58.40,20.240,...,sold,122.12,LOW,Silty clay,False,100,1.0,Poorly drained,plastic,False
49903,342,4340,2019,corn,75.313,Illinois,Ford County,Central Illinois,164.00,170.002,...,sold,122.12,LOW,Silty clay,False,93,1.0,Poorly drained,plastic,False

In [ ]:
fldDataC['tenure'] = fldDataC['tenure'].astype(str)
fldDataC.to_feather('/content/drive/MyDrive/data/pcm-2025/fldData.feather')
fldDataC.to_csv('/content/drive/MyDrive/data/pcm-2025/fldData.csv',index=False)

In [ ]:
fldDataC

Warning: total number of rows (49904) exceeds max_rows (20000). Falling back to pandas display.

,farmId,fieldId,year,crop,acres,stateNm,ctyNm,mrtnLoc,yld,nit,...,tenure,sprRating,sprClass,soilTex,manure,tilScore,covCropS,drainCl,drainType,irr
0,0,0,2019,soybeansSeed,50.253,Illinois,McLean County,Central Illinois,69.00,0.000,...,own,141.73,HIGH,Silt loam,False,35,1.0,Somewhat poorly drained,plastic,False
1,0,1,2019,soybeansSeed,53.225,Illinois,McLean County,Central Illinois,69.00,0.000,...,own,141.82,HIGH,Silt loam,False,35,1.0,Somewhat poorly drained,none,False
2,1,2,2020,corn,32.170,Illinois,Livingston County,Central Illinois,142.00,195.402,...,Blank,115.52,LOW,Silty clay loam,False,40,1.0,Somewhat poorly drained,none,False
3,1,3,2020,corn,35.379,Illinois,Livingston County,Central Illinois,142.00,195.402,...,rent,117.50,LOW,Silty clay loam,False,40,1.0,Somewhat poorly drained,plastic,False
4,2,4,2020,soybeans,39.950,Illinois,Champaign County,Central Illinois,71.28,0.000,...,Blank,143.13,HIGH,Silt loam,False,35,1.0,Somewhat poorly drained,none,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49899,342,3320,2020,soybeans,160.000,Illinois,Ford County,Central Illinois,55.20,0.000,...,rent,118.18,LOW,Silty clay,False,100,1.0,Poorly drained,none,False
49900,342,3320,2019,corn,160.000,Illinois,Ford County,Central Illinois,130.00,170.002,...,rent,118.18,LOW,Silty clay,False,93,1.0,Poorly drained,none,False
49901,342,4340,2020,soybeans,75.313,Illinois,Ford County,Central Illinois,58.40,0.000,...,sold,122.12,LOW,Silty clay,False,100,1.0,Poorly drained,plastic,False
49902,342,4340,2021,soybeansSeed,75.313,Illinois,Ford County,Central Illinois,58.40,20.240,...,sold,122.12,LOW,Silty clay,False,100,1.0,Poorly drained,plastic,False
49903,342,4340,2019,corn,75.313,Illinois,Ford County,Central Illinois,164.00,170.002,...,sold,122.12,LOW,Silty clay,False,93,1.0,Poorly drained,plastic,False