<a href="https://colab.research.google.com/github/gschnitkey/PCM/blob/main/lowInputAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np


from google.colab import data_table
data_table.enable_dataframe_formatter()

# Low Input Analysis

This program does the first work on low input

In [ ]:
fldData = pd.read_feather('/content/drive/MyDrive/data/pcm-2025/fldData.feather')
passData  = pd.read_feather('/content/drive/MyDrive/data/pcm-2025/passData.feather')

In [ ]:
# Create a pandas DataFrame that sums n, p, k, ai by farm, field, year
summed_df = passData.groupby(['farmId', 'fieldId', 'year'])[['n', 'p', 'k', 'ai']].sum().reset_index()

# Display the resulting DataFrame
summed_df

Warning: total number of rows (44458) exceeds max_rows (20000). Falling back to pandas display.

       farmId  fieldId  year           n       p      k    ai
0           0      0.0  2018  202.012672  104.00  120.0  10.0
1           0      0.0  2019    0.000000    0.00    0.0   8.0
2           0      0.0  2020  217.013728  104.00   90.0   9.0
3           0      0.0  2021    0.000000    0.00    0.0  11.0
4           0      0.0  2022  216.946156   61.18  108.0  11.0
...       ...      ...   ...         ...     ...    ...   ...
44453     843  12071.0  2016  175.593160   92.00  120.0   5.0
44454     843  12071.0  2017    0.000000    0.00    0.0   4.0
44455     843  12072.0  2015    0.000000    0.00    0.0   4.0
44456     843  12072.0  2016  175.593160   92.00  120.0   5.0
44457     843  12072.0  2017    0.000000    0.00    0.0   5.0

[44458 rows x 7 columns]

In [ ]:
# Merge summed_df with fldData
fldData = pd.merge(fldData,
                   summed_df,
                   on=['farmId', 'fieldId', 'year'],
                   how='left')

# Display the fldData with the new columns
fldData[['farmId', 'fieldId', 'year', 'n', 'p', 'k', 'ai']].head()

   farmId  fieldId  year           n     p      k   ai
0       0        0  2019    0.000000   0.0    0.0  8.0
1       0        1  2019    0.000000   0.0    0.0  8.0
2       1        2  2020  195.401856  72.8  108.0  3.0
3       1        3  2020  195.401856  72.8  108.0  3.0
4       2        4  2020    0.000000   0.0    0.0  4.0

In [ ]:
fldData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49904 entries, 0 to 49903
Data columns (total 48 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   farmId        49904 non-null  int64
 1   fieldId       49904 non-null  int64
 2   year          49904 non-null  int64
 3   crop          49904 non-null  object
 4   acres         49904 non-null  float64
 5   stateNm       49904 non-null  object
 6   ctyNm         49904 non-null  object
 7   mrtnLoc       42555 non-null  object
 8   yld           49904 non-null  float64
 9   nit           49904 non-null  float64
 10  phos          49904 non-null  float64
 11  pot           49904 non-null  float64
 12  lime          49904 non-null  float64
 13  rev           49904 non-null  float64
 14  pltDate       49902 non-null  datetime64[ns]
 15  nonLandCst    49904 non-null  float64
 16  harDate       49902 non-null  datetime64[ns]
 17  olr           49904 non-null  float64
 18  nStand        28603 non-null  object
 19  dirCst        49904 non-null  float64
 20  covStand      49904 non-null  object
 21  pwrCst        49904 non-null  float64
 22  tilStand      49904 non-null  object
 23  ovedCst       49904 non-null  int64
 24  nBench        28603 non-null  object
 25  nitCost       49904 non-null  float64
 26  pcmField      49904 non-null  bool
 27  fldWorkCost   49904 non-null  float64
 28  system        49904 non-null  object
 29  nMgtS         49904 non-null  int64
 30  covCropPlant  49904 non-null  float64
 31  type          49900 non-null  object
 32  covCropSeed   49904 non-null  float64
 33  seedType      49893 non-null  object
 34  tenure        49904 non-null  object
 35  sprRating     49903 non-null  float64
 36  sprClass      49904 non-null  object
 37  soilTex       49903 non-null  object
 38  manure        49904 non-null  bool
 39  tilScore      49904 non-null  int64
 40  covCropS      48864 non-null  float64
 41  drainCl       49903 non-null  object
 42  drainType     49904 non-null  object
 43  irr           49904 non-null  bool
 44  n             45319 non-null  float64
 45  p             45319 non-null  float64
 46  k             45319 non-null  float64
 47  ai            45319 non-null  float64
dtypes: bool(3), datetime64[ns](2), float64(21), int64(6), object(16)
memory usage: 17.3+ MB

In [ ]:
wrkData = fldData[fldData['mrtnLoc'] == 'Central Illinois'].copy()
wrkData = wrkData[wrkData['crop'] == 'corn'].copy()
wrkData = wrkData[wrkData['covStand'] == 'No Cover Crop'].copy()
wrkData = wrkData[wrkData['covStand'] == 'No Cover Crop'].copy()
wrkData = wrkData[wrkData['sprClass'] == 'HIGH'].copy()
wrkData.head()

Warning: Total number of columns (48) exceeds max_columns (20). Falling back to pandas display.

,farmId,fieldId,year,crop,acres,stateNm,ctyNm,mrtnLoc,yld,nit,...,manure,tilScore,covCropS,drainCl,drainType,irr,n,p,k,ai
5,3,5,2020,corn,39.340,Illinois,Vermilion County,Central Illinois,232.0,199.763,...,False,85,1.0,Poorly drained,none,False,199.76280,57.500000,105.000000,7.0
6,3,6,2020,corn,40.358,Illinois,Vermilion County,Central Illinois,232.0,199.763,...,False,85,1.0,Moderately well drained,none,False,199.76280,57.500000,105.000000,7.0
19,10,19,2020,corn,41.693,Illinois,Woodford County,Central Illinois,195.0,180.847,...,False,93,1.0,Somewhat poorly drained,plastic,False,180.84658,96.990764,142.022296,7.0
20,10,20,2020,corn,44.000,Illinois,Woodford County,Central Illinois,195.0,180.847,...,False,93,1.0,Somewhat poorly drained,none,False,180.84658,96.990764,142.022296,7.0
21,11,21,2020,corn,78.370,Illinois,Champaign County,Central Illinois,274.0,201.000,...,False,93,1.0,Poorly drained,none,False,201.00000,73.600000,48.000000,10.0

In [ ]:
wrkData['pcmField'].unique()

array([ True, False])

In [ ]:
# Calculate the average of 'ai' in wrkData
average_ai = wrkData['ai'].mean()
print(f"Average of 'ai': {average_ai:.2f}")

Average of 'ai': 7.17

In [ ]:
# Calculate the average of 'ai' by year in wrkData
average_ai_by_year = wrkData.groupby('year')['ai'].mean().reset_index()
print("Average of 'ai' by Year:")
print(average_ai_by_year)

Average of 'ai' by Year:
    year        ai
0   2015  4.264706
1   2016  4.892000
2   2017  5.412664
3   2018  5.385000
4   2019  5.717158
5   2020  6.166477
6   2021  6.891852
7   2022  7.777778
8   2023  8.033144
9   2024  8.981308
10  2025  8.698589

In [ ]:
# Calculate the average of 'nit' by year in wrkData
average_nit_by_year = wrkData.groupby('year')['nit'].mean().reset_index()
print("Average of 'nit' by Year:")
print(average_nit_by_year)

Average of 'nit' by Year:
    year         nit
0   2015  208.942764
1   2016  209.137255
2   2017  208.737091
3   2018  208.658811
4   2019  206.194638
5   2020  209.683141
6   2021  210.404888
7   2022  210.726102
8   2023  214.901129
9   2024  213.241689
10  2025  210.229205

In [ ]:
# Define bins and labels for nRateCat
bins = [-np.inf, 150, 200, 235, np.inf]
labels = [1, 2, 3, 4]

# Create the nRateCat variable using pd.cut
wrkData['nRateCat'] = pd.cut(wrkData['nit'], bins=bins, labels=labels, right=False)

# Display the counts of each category to verify
print("Counts of nRateCat categories:")
print(wrkData['nRateCat'].value_counts())

Counts of nRateCat categories:
nRateCat
3    4005
2    2533
4    1448
1     185
Name: count, dtype: int64

In [ ]:
# Calculate the frequency of nRateCat categories by year
category_frequency_by_year = wrkData.groupby(['year', 'nRateCat']).size().unstack(fill_value=0)

print("Frequency of nRateCat Categories by Year:")
display(category_frequency_by_year)

Frequency of nRateCat Categories by Year:

/tmp/ipykernel_3655/4079565869.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  category_frequency_by_year = wrkData.groupby(['year', 'nRateCat']).size().unstack(fill_value=0)

nRateCat   1    2    3    4
year
2015       4   38   40   24
2016       8   83  126   46
2017      20  140  236   78
2018       4  216  311  100
2019      21  285  406  124
2020      10  352  426  143
2021       4  252  381  123
2022      16  326  461  149
2023      38  281  529  247
2024      27  288  567  226
2025      33  272  522  188

In [ ]:
# Calculate the average of 'OFR' by category and year
average_ofr_by_category_year = wrkData.groupby(['year', 'nRateCat'])['olr'].mean().unstack(fill_value=0)

print("Average of OFR by nRateCat Category and Year:")
display(average_ofr_by_category_year)

Average of OFR by nRateCat Category and Year:

/tmp/ipykernel_3655/4235261330.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  average_ofr_by_category_year = wrkData.groupby(['year', 'nRateCat'])['olr'].mean().unstack(fill_value=0)

nRateCat           1           2           3           4
year
2015      131.802500  205.520000  222.146250  194.161250
2016      253.253750  271.017229  260.952937  231.351304
2017      221.201500  200.087571  209.150339  211.503462
2018      365.487500  330.382222  320.338232  315.858400
2019      275.189048  276.458070  251.632143  246.236935
2020      175.629000  312.663068  313.346667  288.628392
2021      544.630000  585.063135  599.948478  605.885447
2022      761.914375  777.217546  759.797397  733.363624
2023      376.186579  323.531459  279.007618  266.567854
2024      206.849630  258.355139  239.266420  226.367212
2025      371.225152  271.770735  242.495249  214.239681

In [ ]:
# Calculate the average of 'ai' by nRateCat category
average_ai_by_nRateCat = wrkData.groupby('nRateCat')['ai'].mean().reset_index()

print("Average of 'ai' by nRateCat Category:")
display(average_ai_by_nRateCat)

Average of 'ai' by nRateCat Category:

/tmp/ipykernel_3655/2496604403.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  average_ai_by_nRateCat = wrkData.groupby('nRateCat')['ai'].mean().reset_index()

  nRateCat        ai
0        1  6.534161
1        2  7.052524
2        3  7.241727
3        4  7.284382

In [ ]:
# Calculate the average of 'ai' by nRateCat and year
average_ai_by_nRateCat_year = wrkData.groupby(['year', 'nRateCat'])['ai'].mean().unstack(fill_value=0)

print("Average of 'ai' by nRateCat Category and Year:")
display(average_ai_by_nRateCat_year)

Average of 'ai' by nRateCat Category and Year:

/tmp/ipykernel_3655/996055635.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  average_ai_by_nRateCat_year = wrkData.groupby(['year', 'nRateCat'])['ai'].mean().unstack(fill_value=0)

nRateCat          1         2         3         4
year
2015       4.000000  4.447368  4.050000  4.400000
2016       7.250000  4.837500  4.669421  5.195122
2017       6.550000  5.444444  5.377682  5.142857
2018       4.500000  5.304569  5.315961  5.826087
2019       5.894737  5.750000  5.689840  5.696629
2020       8.200000  6.189911  6.178922  5.893443
2021      12.000000  6.958159  6.862385  6.787037
2022       6.562500  7.790769  7.665208  8.294574
2023       6.257143  7.395683  8.478011  8.063636
2024       6.750000  9.138790  9.026882  8.862559
2025       6.833333  9.231939  8.715385  8.135135

In [ ]:
# Calculate the frequency of 'ai' by year
ai_frequency_by_year = wrkData.groupby(['year', 'ai']).size().unstack(fill_value=0)

print("Frequency of 'ai' by Year:")
display(ai_frequency_by_year)

Frequency of 'ai' by Year:

ai,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0
year,,,,,,,,,,,,,,,,,,,,
2015,0,0,3,12,60,12,12,3,0,0,0,0,0,0,0,0,0,0,0,0
2016,0,0,9,21,101,42,53,3,8,7,4,2,0,0,0,0,0,0,0,0
2017,0,5,11,35,147,60,91,34,35,18,16,3,1,0,2,0,0,0,0,0
2018,0,5,31,48,166,97,107,35,48,31,31,1,0,0,0,0,0,0,0,0
2019,1,5,42,43,135,123,175,74,57,46,41,4,0,0,0,0,0,0,0,0
2020,3,5,26,33,141,129,218,96,74,88,31,28,4,1,0,0,0,0,0,0
2021,1,0,6,25,81,66,118,115,116,68,36,24,13,6,0,0,0,0,0,0
2022,0,0,3,30,37,60,151,181,154,105,61,75,41,17,12,0,0,0,0,0
2023,0,1,1,6,45,63,189,131,190,200,56,107,26,30,8,3,0,0,0,0
2024,0,0,0,13,29,101,95,71,151,166,103,135,80,90,22,3,6,4,0,1
2025,0,0,2,36,5,51,136,126,148,111,111,104,95,25,20,1,13,5,3,0

In [ ]:
# Define bins and labels for aiCat
bins_ai = [-np.inf, 3, 8, 12, np.inf]
labels_ai = [1, 2, 3, 4]

# Create the aiCat variable using pd.cut
wrkData['aiCat'] = pd.cut(wrkData['ai'], bins=bins_ai, labels=labels_ai, right=True)

# Display the counts of each category to verify
print("Counts of aiCat categories:")
print(wrkData['aiCat'].value_counts())

# Display the first few rows with the new column
display(wrkData[['ai', 'aiCat']].head())

Counts of aiCat categories:
aiCat
2    4946
3    2073
1     462
4     272
Name: count, dtype: int64

      ai aiCat
5    7.0     2
6    7.0     2
19   7.0     2
20   7.0     2
21  10.0     3

In [ ]:
# Calculate the average of 'olr' by aiCat and year
average_olr_by_aiCat_year = wrkData.groupby(['year', 'aiCat'])['olr'].mean().unstack(fill_value=0)

print("Average of OLR by aiCat Category and Year:")
display(average_olr_by_aiCat_year)

Average of OLR by aiCat Category and Year:

/tmp/ipykernel_3655/321377235.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  average_olr_by_aiCat_year = wrkData.groupby(['year', 'aiCat'])['olr'].mean().unstack(fill_value=0)

aiCat           1           2           3           4
year
2015   298.399333  198.260115         NaN         NaN
2016   313.528667  257.678889  245.724615         NaN
2017   245.709216  211.418965  185.208947  132.040000
2018   367.452024  331.426623  264.731587         NaN
2019   330.140769  264.639379  226.315165         NaN
2020   384.792388  323.969225  274.606556  308.240000
2021   698.413437  599.663851  578.582979  531.590000
2022   763.558788  758.650909  765.817482  816.261379
2023   395.686250  309.780615  254.772699  228.628293
2024   379.096923  279.967517  209.920640  176.844048
2025   322.332368  262.171030  232.818385  156.807313

In [ ]:
average_yld_by_aiCat = wrkData.groupby('aiCat')['yld'].mean().reset_index()

print("Average of Yield by aiCat Category:")
display(average_yld_by_aiCat)

Average of Yield by aiCat Category:

/tmp/ipykernel_3655/3794099617.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  average_yld_by_aiCat = wrkData.groupby('aiCat')['yld'].mean().reset_index()

  aiCat         yld
0     1  207.884306
1     2  220.468522
2     3  233.037636
3     4  243.397572

In [ ]:
average_yld_by_aiCat_year = wrkData.groupby(['year', 'aiCat'])['yld'].mean().unstack(fill_value=0)

print("Average of Yield by aiCat Category and Year:")
display(average_yld_by_aiCat_year)

Average of Yield by aiCat Category and Year:

/tmp/ipykernel_3655/4163904602.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  average_yld_by_aiCat_year = wrkData.groupby(['year', 'aiCat'])['yld'].mean().unstack(fill_value=0)

aiCat           1           2           3           4
year
2015   187.625000  188.122901         NaN         NaN
2016   217.486061  219.403345  242.007143         NaN
2017   204.126737  215.949859  227.416667  217.000000
2018   222.974326  228.268850  238.374416         NaN
2019   189.873476  200.045874  204.951429         NaN
2020   200.786143  211.107866  215.487005  245.000000
2021   205.642857  215.905609  220.307313  198.500000
2022   208.046875  223.589555  233.078408  248.013514
2023   217.681818  225.217833  231.721018  230.525094
2024   242.764706  235.234878  240.474240  248.748301
2025   239.808462  234.916777  240.072189  244.518913

In [ ]:
average_nit_by_aiCat_year = wrkData.groupby(['year', 'aiCat'])['nit'].mean().unstack(fill_value=0)

print("Average of NIT by aiCat Category and Year:")
display(average_nit_by_aiCat_year)

Average of NIT by aiCat Category and Year:

/tmp/ipykernel_3655/674322951.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  average_nit_by_aiCat_year = wrkData.groupby(['year', 'aiCat'])['nit'].mean().unstack(fill_value=0)

aiCat           1           2           3           4
year
2015   206.629000  200.143496         NaN         NaN
2016   201.516818  208.281821  193.044214         NaN
2017   206.546611  208.693266  203.107437  189.646000
2018   203.088184  207.468417  218.258922         NaN
2019   193.306220  202.019515  206.030202         NaN
2020   203.356693  206.677321  203.234964  211.454000
2021   202.896786  207.316575  205.325005  186.553250
2022   203.115750  205.238189  206.419260  218.031189
2023   195.911000  206.943073  212.970543  210.988453
2024   206.649824  207.222847  214.058297  208.374497
2025   230.736577  209.471855  207.596342  209.868935

In [ ]:
average_n_by_aiCat = wrkData.groupby('aiCat')['n'].mean().reset_index()

print("Average of N Rate by aiCat Category:")
display(average_n_by_aiCat)

Average of N Rate by aiCat Category:

/tmp/ipykernel_3655/1363027541.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  average_n_by_aiCat = wrkData.groupby('aiCat')['n'].mean().reset_index()

  aiCat           n
0     1  207.602496
1     2  208.522015
2     3  211.744048
3     4  209.115900

In [ ]:
average_n_by_aiCat_year = wrkData.groupby(['year', 'aiCat'])['n'].mean().unstack(fill_value=0)

print("Average of N Rate by aiCat Category and Year:")
display(average_n_by_aiCat_year)

Average of N Rate by aiCat Category and Year:

/tmp/ipykernel_3655/889251734.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  average_n_by_aiCat_year = wrkData.groupby(['year', 'aiCat'])['n'].mean().unstack(fill_value=0)

aiCat           1           2           3           4
year
2015   210.246587  203.083168         NaN         NaN
2016   199.938396  210.389006  192.151635         NaN
2017   207.419361  208.852713  199.159388  189.646000
2018   203.506039  208.837148  215.937844         NaN
2019   200.089169  204.470150  205.967206         NaN
2020   208.062309  207.881119  200.492500  211.454200
2021   207.280452  210.790235  207.644252  183.121112
2022   204.419962  205.668997  210.952522  217.205400
2023   218.320186  209.256951  217.856477  208.364773
2024   207.404267  211.891333  216.032759  208.040606
2025   239.938641  210.898732  209.466602  210.970497

In [ ]:
# Calculate the average 'n' for each year
average_n_per_year = wrkData.groupby('year')['n'].transform('mean')

# Create the nAvg variable: 1 if 'n' is less than the yearly average, 0 otherwise
wrkData['nAvg'] = (wrkData['n'] < average_n_per_year).astype(int)

print("First 5 rows of wrkData with the new 'nAvg' variable:")
display(wrkData[['year', 'n', 'nAvg']].head())

First 5 rows of wrkData with the new 'nAvg' variable:

    year          n  nAvg
5   2020  199.76280     1
6   2020  199.76280     1
19  2020  180.84658     1
20  2020  180.84658     1
21  2020  201.00000     1

In [ ]:
# Calculate the average 'ai' for each year
average_ai_per_year = wrkData.groupby('year')['ai'].transform('mean')

# Create the aiAvg variable: 1 if 'ai' is less than the yearly average, 0 otherwise
wrkData['aiAvg'] = (wrkData['ai'] < average_ai_per_year).astype(int)

print("First 5 rows of wrkData with the new 'aiAvg' variable:")
display(wrkData[['year', 'ai', 'aiAvg']].head())

First 5 rows of wrkData with the new 'aiAvg' variable:

    year    ai  aiAvg
5   2020   7.0      0
6   2020   7.0      0
19  2020   7.0      0
20  2020   7.0      0
21  2020  10.0      0

In [ ]:
wrkData['low'] = wrkData['nAvg'] + wrkData['aiAvg']
wrkData['low'].unique()

average_olr_by_low_year = wrkData.groupby(['year', 'low'])['olr'].mean().unstack(fill_value=0)

print("Average of OLR by 'low' Category and Year:")
display(average_olr_by_low_year)

Average of OLR by 'low' Category and Year:

low            0           1           2
year
2015  145.200625  207.138077  231.271053
2016  220.828462  269.665673  281.146173
2017  180.176250  199.106884  242.232721
2018  275.060982  334.210893  349.050798
2019  223.910032  266.848933  315.247778
2020  238.865297  313.647538  350.013647
2021  584.429711  600.776909  605.067320
2022  762.862450  752.897996  775.973937
2023  257.035159  280.853018  330.311879
2024  206.787278  242.217651  292.695748
2025  228.109793  245.465000  278.735103

In [ ]:
wrkData['tilLow'] = wrkData['tilStand'].isin(['No Till', 'Strip Till']).astype(int)

print("First 5 rows of wrkData with the new 'tilLow' variable:")
display(wrkData[['tilStand', 'tilLow']].head())

First 5 rows of wrkData with the new 'tilLow' variable:

        tilStand  tilLow
5   1-Pass Light       0
6   1-Pass Light       0
19    Strip Till       1
20    Strip Till       1
21    Strip Till       1

In [ ]:
wrkData['lowTil'] = wrkData['nAvg'] + wrkData['aiAvg'] + wrkData['tilLow']
wrkData['lowTil'].unique()

average_olr_by_lowTil_year = wrkData.groupby(['year', 'lowTil'])['olr'].mean().unstack(fill_value=0)

print("Average of OLR by 'lowTil' Category and Year:")
display(average_olr_by_lowTil_year)

Average of OLR by 'lowTil' Category and Year:

lowTil           0           1           2           3
year
2015    100.251250  208.595918  244.855429  163.538571
2016    214.135439  266.327339  279.522754  268.579286
2017    177.205204  199.191935  221.994714  255.959400
2018    282.947559  324.098449  340.323585  352.095319
2019    233.266273  252.661253  292.913551  301.051143
2020    213.163592  319.663622  325.012751  358.331356
2021    588.951452  598.110806  607.976445  538.833778
2022    727.958655  757.093602  775.045403  769.871236
2023    270.781409  262.312977  307.417514  331.561472
2024    215.607043  230.880600  251.767358  294.081495
2025    223.534455  246.862027  250.242925  274.124000

In [ ]:
average_yld_by_lowTil_year = wrkData.groupby(['year', 'lowTil'])['yld'].mean().unstack(fill_value=0)

print("Average of Yield by 'lowTil' Category and Year:")
display(average_yld_by_lowTil_year)

Average of Yield by 'lowTil' Category and Year:

lowTil           0           1           2           3
year
2015    168.875000  201.775510  204.531429  179.214286
2016    221.177544  229.208165  222.840290  213.928571
2017    221.330000  221.137527  217.133429  224.510000
2018    233.781890  235.695714  230.520000  226.467021
2019    212.092909  209.370599  206.884393  207.714286
2020    203.125282  221.163699  214.796361  218.114576
2021    228.060054  224.860879  220.817500  199.991333
2022    233.078571  236.645081  230.156075  222.505618
2023    236.031409  236.013133  231.366749  230.671574
2024    245.365261  245.405150  246.211617  238.967383
2025    235.832364  248.129541  242.974875  227.852222

In [ ]:
fields_by_lowTil_year = wrkData.groupby(['year', 'lowTil'])['fieldId'].nunique().unstack(fill_value=0)

print("Number of Fields by 'lowTil' Category and Year:")
display(fields_by_lowTil_year)

Number of Fields by 'lowTil' Category and Year:

lowTil    0    1    2    3
year
2015      8   49   35   14
2016     57  109   69   28
2017     98  186  140   50
2018    127  245  212   47
2019    220  367  214   35
2020    142  392  338   59
2021    186  273  256   45
2022    119  372  372   89
2023    149  383  366  197
2024    230  400  371  107
2025    110  370  400  135

In [ ]:
average_olr_by_aiAvg_year = wrkData.groupby(['year', 'aiAvg'])['olr'].mean().unstack(fill_value=0)

print("Average of OLR by 'aiAvg' Category and Year:")
display(average_olr_by_aiAvg_year)

Average of OLR by 'aiAvg' Category and Year:

aiAvg           0           1
year
2015   159.368387  225.896933
2016   244.197500  273.348244
2017   175.864398  233.745465
2018   294.385423  347.060749
2019   238.464825  289.779885
2020   258.826277  340.999189
2021   583.139330  615.236364
2022   766.210061  756.836364
2023   264.466546  310.878450
2024   211.019336  282.769000
2025   232.116086  266.707004

In [ ]:
average_yld_by_aiAvg_year = wrkData.groupby(['year', 'aiAvg'])['yld'].mean().unstack(fill_value=0)

print("Average of Yield by 'aiAvg' Category and Year:")
display(average_yld_by_aiAvg_year)

Average of Yield by 'aiAvg' Category and Year:

aiAvg           0           1
year
2015   185.258065  202.168000
2016   226.291970  222.032443
2017   219.205694  221.308798
2018   234.517254  231.547666
2019   210.063142  208.429685
2020   210.671569  219.454739
2021   224.724104  219.824310
2022   237.587816  226.777814
2023   236.030000  231.607300
2024   246.905756  242.424261
2025   245.048513  239.047024

In [ ]:
count_observations_by_aiAvg_year = wrkData.groupby(['year', 'aiAvg']).size().unstack(fill_value=0)

print("Count of Observations by 'aiAvg' Category and Year:")
display(count_observations_by_aiAvg_year)

Count of Observations by 'aiAvg' Category and Year:

aiAvg    0    1
year
2015    31   75
2016   132  131
2017   216  258
2018   284  347
2019   487  349
2020   376  555
2021   463  297
2022   490  462
2023   469  626
2024   648  460
2025   511  504

In [ ]:
average_olr_by_nAvg_year = wrkData.groupby(['year', 'nAvg'])['olr'].mean().unstack(fill_value=0)

print("Average of OLR by 'nAvg' Category and Year:")
display(average_olr_by_nAvg_year)

Average of OLR by 'nAvg' Category and Year:

nAvg           0           1
year
2015  197.682642  215.198302
2016  236.409375  279.868815
2017  199.835481  215.031319
2018  309.451770  337.838414
2019  241.794762  287.352380
2020  294.097169  323.117091
2021  598.662542  591.981652
2022  749.483085  772.904162
2023  272.734699  308.259076
2024  234.631277  247.970097
2025  242.326581  256.135508

In [ ]:
average_yld_by_nAvg_year = wrkData.groupby(['year', 'nAvg'])['yld'].mean().unstack(fill_value=0)

print("Average of Yield by 'nAvg' Category and Year:")
display(average_yld_by_nAvg_year)

Average of Yield by 'nAvg' Category and Year:

nAvg           0           1
year
2015  201.067925  193.377358
2016  224.416328  223.937037
2017  222.859121  217.799021
2018  234.397174  231.307605
2019  209.691687  208.909940
2020  216.576110  215.161409
2021  227.014228  217.587286
2022  235.154289  229.745192
2023  235.907086  231.228544
2024  245.605664  244.395166
2025  244.408370  239.769688